### ISSUE TITLE
HOME page update

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/projects_website#101]
Update home page to this:

![ACI_home](https://user-images.githubusercontent.com/20182572/91153027-59a42a00-e6c8-11ea-99e3-ece9f2a497e0.png)

**Text:**

The Alliance for a (size: 50px)
Conscious Internet (size: 100px)

......

A collective ecosystem of planet and human centric projects co-creating a new peer-to-peer internet. (size: 50px)

.....

We aim to empower +1 Billion people with access to internet, complementary education and currencies (banking) for less than $1 per month.

We replace competition with collaboration and ego with love because we know that only together do we stand a chance to reach our goal.

We collaborate with one another to improve our solutions, efficiency, reach, visibility and service for the planet and humanity.
(size: 16px)
.....

If not us, who? If not now, when? (size: 50px)

**Files:**

(please provide image size to make it fit properly)
![half_earth](https://user-images.githubusercontent.com/20182572/91159231-704e7f00-e6d0-11ea-9faf-43d6c469f708.png)

![hand1](https://user-images.githubusercontent.com/20182572/91158780-d555a500-e6cf-11ea-85ba-7f213253ab8d.png)

![ACI_ICON](https://user-images.githubusercontent.com/20182572/91158849-ebfbfc00-e6cf-11ea-8cea-0efd11e62887.png)

![ACI_TEXT-LOGO](https://user-images.githubusercontent.com/20182572/91158880-f4eccd80-e6cf-11ea-9c10-0c5d68aae996.png)

**Comment by samaradel** [comment]
@Vilnite First image has a very bad resolution can you provide another one please

**Comment by Vilnite** [comment]
> @Vilnite First image has a very bad resolution can you provide another one please

will send you on telegram :)

**Comment by Vilnite** [comment]
@ehab-hassan can we update the below text to:
We aim to empower 1+ Billion people with access to the internet allowing everyone a chance to exchange value, goods and information for less than $1 per month.

Independent of location, race, gender, religion we leave no one behind so that everyone can deliver services or products to everyone in all transparency and fairness. 

We collaborate with one another to improve our solutions, efficiency, reach, visibility and our service to the planet and humanity.


As well as already discussed fixes:

<img width="1440" alt="Screenshot 2020-09-14 at 18 25 58" src="https://user-images.githubusercontent.com/20182572/93180069-46bccc80-f73f-11ea-89b9-71ea2b582aeb.png">

**Comment by Vilnite** [comment]
We are almost there @samaradel :
![homepage](https://user-images.githubusercontent.com/20182572/94829023-c5d62400-0412-11eb-9566-8ea8fa4f330b.png)


where 
The Alliance for a (60px, #00A788)
Conscious Internet (100px, #00A788)

sub-text (30px , #12B1A4) please change to:
"A planetary movement of people and organisations that take action now to shape a conscious digital world that empowers everyone equally, across borders."

Font: Roboto

Please update the text that goes below (copy paste the one below) accordingly with matching font (Roboto) and color (#00A788):
"We aim to empower 1+ Billion people with access to the Internet allowing everyone a chance to exchange value, goods and information for less than $1 per month.

Independent of location, race, gender, religion we leave no one behind so that everyone can deliver services and goods to everyone in all transparency and fairness.

Instead of competing we collaborate with one another to improve our solutions, efficiency, reach, visibility and our service to the planet and humanity."

**Comment by Vilnite** [comment]
Also footer still runs over the text:
<img width="1550" alt="Screenshot 2020-10-04 at 12 32 05" src="https://user-images.githubusercontent.com/20182572/95011978-91927b80-063d-11eb-8106-c9b2d9572199.png">

Going waaayy out of line when minimising the screen:

<img width="1240" alt="Screenshot 2020-10-04 at 12 32 18" src="https://user-images.githubusercontent.com/20182572/95011997-b4bd2b00-063d-11eb-8d00-cb48bf7390d4.png">

**Comment by samaradel** [comment]
fixed on staging

**Comment by Vilnite** [comment]
Excellent @samaradel , thank you! :)

**Comment by Vilnite** [comment]
@samaradel can we make it as close to this as possible? If we compare it's quite off still.
https://xd.adobe.com/view/8c4987c1-7622-4485-784e-107f53407b3d-fa78/?fullscreen&hints=off

1. remove space between letters for Alliance for a Conscious Internet
2. Move the hand with a planet closer to the text (more centred)

We paid to design ACI website, let's use it. :)

There are dev specs for it as well for css details:
https://xd.adobe.com/view/e785bb90-e0c6-47c1-4452-ea4d60e9b069-91b4/specs/

**Comment by ehab-hassan** [comment]
done at staging
I try to be nearest to  your template but please put in ur mind that is different instruction we have (the old template we worked before) also ur guide is wide and we work at full width 1920 so there will be some space

**Comment by Vilnite** [comment]
This text stretches too far:
<img width="1552" alt="Screenshot 2020-10-13 at 11 14 56" src="https://user-images.githubusercontent.com/20182572/95834526-c2616780-0d45-11eb-82d8-b503a27c7c52.png">

**Comment by ehab-hassan** [comment]
done
