### ISSUE TITLE
Add Join the Alliance Page

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/projects_website#25]
All the content for Join the Alliance page is in this doc (page 2):

https://docs.google.com/document/d/1yeUfEvfvKOZHn9YNmFzD3IoqBPJwjLi3txcKiMam3SE/edit?usp=sharing
![equality](https://user-images.githubusercontent.com/20182572/81055396-e718ff80-8ec8-11ea-9120-4a0d97a9bd2c.png)

Will need a simple reach out form linking to my email (kristine@threefold.io)

Also, let's make sure the Landing page (page 1) text is updated on website (there are small edits in that text)

- [x] Implement Join us page
- [x] Improve Styling

**Comment by Hamdy** [comment]
- Added support for sending email via backend
- Implemented join us page

waiting for UI team to finish styling of the page
