### ISSUE TITLE
CIA: Update open graph tags for all pages please

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/projects_website#29]
Please let me know if anything is confusing!

For main page:

Title: Conscious Internet Alliance
Image: Header Image from main page
Description: A collective and open ecosystem of planet and human centric projects.

For project pages please do:

Title: Project Name | Conscious Internet Alliance
Image: Project Image
Description: Use the line of text being used underneath the project image

Example below of project image and line of text:
<img width="801" alt="Screen Shot 2020-05-05 at 7 14 34 PM" src="https://user-images.githubusercontent.com/50134479/81095037-b3f46180-8f04-11ea-9aab-fcb6e6471e93.png">

For people pages please do:

Title: Person Name | Conscious Internet Alliance
Image: Image from this GitHub folder: https://github.com/threefoldfoundation/www_threefold_ecosystem/tree/development/info/people
Description: None

**Comment by Hamdy** [comment]
done

**Comment by samtaggart** [comment]
Hi @Hamdy, can you please re-look at this. It would be best if each page had specific open graph tag. If too difficult or too much work, let me know.

They're not showing up yet also (tried to share on Facebook etc) but I'm guessing there might just be some sort of delay. I saw the tag has been implemented across the site.
