### ISSUE TITLE
Add Wisdom Council Page

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/projects_website#52]
Add Wisdom Council between People and Join Us (in navigation bar)

Content for the page is in this doc (4th page):
https://docs.google.com/document/d/1yeUfEvfvKOZHn9YNmFzD3IoqBPJwjLi3txcKiMam3SE/edit?usp=sharing

Will add image as soon as we have it.

On the bottom is grid (4 columns x 3 rows) of wisdom council members (all has a tag/badge of wisdomcouncil) - image and name, when click on it it opens respective persons page.
1 is missing, this person is still to be decided on.

Let's keep it in staging till we get approval on the page.

**Comment by ehab-hassan** [comment]
@Hamdy can u please clone home page so I can change content to Wisdom Council Page

**Comment by Hamdy** [comment]
@ehab-hassan page added

**Comment by ehab-hassan** [comment]
@Hamdy we need to filter Wisdom Council people's at Wisdom Council page

**Comment by Vilnite** [comment]
Example for wisdom council member showcase grid

![example](https://user-images.githubusercontent.com/20182572/82231204-1e59c880-992d-11ea-82d6-ddc2e8beecfb.png)

**Comment by Hamdy** [comment]
@ehab-hassan filter added, but photos not shown in the proper size please fix
