### ISSUE TITLE
CIA Logo

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/projects_website#55]
CIA needs a logo. Was working on it with Zia but he had really limited time.
Please see what you can come up with.

Here's how far Zia got:

![Logo1](https://user-images.githubusercontent.com/20182572/81832161-79ab4580-953e-11ea-8b82-a967703286ca.png)
![Logo2](https://user-images.githubusercontent.com/20182572/81832184-7ca63600-953e-11ea-88c4-6441bd367a9c.png)
![Logo3](https://user-images.githubusercontent.com/20182572/81832213-862f9e00-953e-11ea-96e6-3237afaf3f40.png)

Please don't take this as a reference or base. 
Logo can look completely different but it should be simple, clean and strong fitting the CIA home image feels of consciousness, awareness, connectivity, yet internet and technology.

**Comment by ehab-hassan** [comment]
[CIA-logo-option.pdf](https://github.com/threefoldfoundation/tfwebserver_projects_people/files/4640234/CIA-logo-option.pdf)
some options
