### ISSUE TITLE
Project Name fix

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/projects_website#56]
Please take project names from Github's Line 1 so it would be displayed same correct way everywhere.
It's - 3Bot, PlanED, DigiByte etc.

![project_names](https://user-images.githubusercontent.com/20182572/81903879-b9b40c00-95c2-11ea-8312-2905e6e43ebd.png)

**Comment by Vilnite** [comment]
It's not just 3Bot, it's all projects that needs to be updated.
PlanED, DigiByte.. 
Easiest is to take name from github - 1st line at project_name.md file for every place where project name appears on website.

**Comment by ehab-hassan** [comment]
name taken from folder name and file.md it can not take from header inside md

**Comment by despiegk** [comment]
needs to come from metadata, not from the markdown
if needed add a field to the metadata

**Comment by Vilnite** [comment]
Please fix project names in this view as well

![Screen Shot 2020-05-21 at 9 10 07 AM](https://user-images.githubusercontent.com/20182572/82533090-ea57f080-9b42-11ea-89bc-dc610caa5ea2.png)
