### ISSUE TITLE
overview page of projects

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/projects_website#61]
- can show upto 100 projects
- picture + description up to 150 markdown chars + tags

in one page we can see all, easily

is not the landing page, its the project overview page

**Comment by despiegk** [comment]
maybe we need a new description field in metadata for the overview page

**Comment by Vilnite** [comment]
Remove people from left bar on project page
Add 3rd column (on the left bar) for all project overview
Increase number of rows (on the left bar) for all project overview

**Comment by Vilnite** [comment]
Add Show All button on top right to see all projects on right scroll view showing project name, image, mission

**Comment by Vilnite** [comment]
Sorry, 3rd column will work when we will have 50+ projects, for now let's leave it 2 columns.

**Comment by Vilnite** [comment]
For Show All project view:

![Screen Shot 2020-05-20 at 3 52 42 PM](https://user-images.githubusercontent.com/20182572/82455439-3bb89f00-9ab3-11ea-92e4-fa8750127528.png)
