### ISSUE TITLE
Wisdom council page

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/projects_website#73]
Remove underscores from names and put this page on production:

![Screen Shot 2020-05-28 at 9 34 39 AM](https://user-images.githubusercontent.com/20182572/83112544-99a64180-a0c6-11ea-8a0c-72ca60e08842.png)

**Comment by samaradel** [comment]
@Vilnite Fixed on staging, Please confirm [#71](https://github.com/threefoldfoundation/tfwebserver_projects_people/issues/71) first before merging
