### ISSUE TITLE
prepare design sources

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/projects_website#78]
what been shared
- desktop: https://xd.adobe.com/view/8c4987c1-7622-4485-784e-107f53407b3d-fa78/?fullscreen&hints=off
- mobile: https://xd.adobe.com/view/03bcb1b5-12e3-4f13-6103-e3eecb96ef6b-758d/?fullscreen&hints=off

Website's content:
https://docs.google.com/document/d/1yeUfEvfvKOZHn9YNmFzD3IoqBPJwjLi3txcKiMam3SE/edit?usp=sharing

**Comment by Vilnite** [comment]
Here are links with all the dev specs:
Web: https://xd.adobe.com/view/e785bb90-e0c6-47c1-4452-ea4d60e9b069-91b4/
Mobile: https://xd.adobe.com/view/d6f5eddd-fb3e-4e95-6e40-ab86fc4ee8f3-a0c4/

If some of the downloaded images turns out in bad quality please let me know and the designer will export/prepare them separately.

**Comment by Vilnite** [comment]
Mobile is also updated.

**Comment by xmonader** [comment]
> Here are links with all the dev specs:
> Web: https://xd.adobe.com/view/e785bb90-e0c6-47c1-4452-ea4d60e9b069-91b4/
> Mobile: https://xd.adobe.com/view/d6f5eddd-fb3e-4e95-6e40-ab86fc4ee8f3-a0c4/
> 
> If some of the downloaded images turns out in bad quality please let me know and the designer will export/prepare them separately.

@ehab-hassan please list all of the required sources / images you couldn't download/use

**Comment by ehab-hassan** [comment]
![fly](https://user-images.githubusercontent.com/10484295/84126214-eaf6ef00-aa3d-11ea-95b5-65b9044d01a5.png)
![ACI_DEV_WEB](https://user-images.githubusercontent.com/10484295/84126228-ed594900-aa3d-11ea-85d0-9956c7b164ef.png)
@Vilnite I cant download these images from the source

**Comment by Vilnite** [comment]
On it.

**Comment by Vilnite** [comment]
@ehab-hassan Here are the images both in png 

![ACI_BUTTERFLIES](https://user-images.githubusercontent.com/20182572/84311122-0dcef380-ab63-11ea-8b38-be524b11d0a2.png)
![ACI_LAYERS-MOBILE](https://user-images.githubusercontent.com/20182572/84311132-1293a780-ab63-11ea-8593-21a0cb9ff59e.png)
![ACI_LAYERS-WEB](https://user-images.githubusercontent.com/20182572/84311139-16bfc500-ab63-11ea-8440-d33ba3ba0a8e.png)

**Comment by Vilnite** [comment]
ahh ok, svg is not supported here, lmk if you prefer svg and I'll send it to you on telegram
