### ISSUE TITLE
prepare the new design template for integration

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/projects_website#79]
blocked on threefoldfoundation/www_conscious_internet#78  threefoldfoundation/data_threefold_projects_friends#39

**Comment by xmonader** [comment]
shouldn't be blocked all decisions been settled on, you can use a place holder for all of the designer data until threefoldfoundation/www_conscious_internet#78 is resolved.

**Comment by xmonader** [comment]
I double checked @ehab-hassan  and @samaradel, and they can't work without having the images ready "needed for page structure/layout, responsiveness and place holders won't work 100% because of images spanning over multiple sections and work will need to be redone" and most of the site actually depends on the images not just the "small amount of text"

HTML content also not extractable from the XD format, so please again send the required data as soon as possible. @Vilnite 

CC @despiegk

**Comment by Vilnite** [comment]
What about project and people pages?
Will provide design sources as soon as I have them.

**Comment by Vilnite** [comment]
Design specs are ready.
