### ISSUE TITLE
design comments and technical decisions

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/projects_website#80]
@ehab-hassan @samaradel @Hamdy here please let's have all of your points regarding the design and functionality

**Comment by xmonader** [comment]
> I want to add to Join Us page a form where people can fill out all the necessary info straight from the ACI website.
> So instead of me going on github and manually copying all the info, people can fill out information themselves in the website, then it goes for approval and if approved it goes on the project/people pages.
> 
> Is this possible?

Not with the current way of work, it's always a data repo that gets reflected in the frontend, not the other way around.

**Comment by Vilnite** [comment]
> > I want to add to Join Us page a form where people can fill out all the necessary info straight from the ACI website.
> > So instead of me going on github and manually copying all the info, people can fill out information themselves in the website, then it goes for approval and if approved it goes on the project/people pages.
> > Is this possible?
> 
> Not with the current way of work, it's always a data repo that gets reflected in the frontend, not the other way around.

Ok, even if not for now, we can't keep doing this manually.
So for us not to be in a spot where we again need to redo the whole site this has to be considered while we are building it.

What is the solution here?
