### ISSUE TITLE
ranking for projects

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/projects_website#81]
implement ranking for projects (only in the data repo, not visible on the website for sure)

- the higher the number the higher rank (5 stars max, 1 star min (or default) )

**Comment by Hamdy** [comment]
ranking support added.
By default, each project has ranking of (1)
@Vilnite  we need to add `rank = {number}` in the `info` section of each project

**Comment by Vilnite** [comment]
Added ranking, it works but now rest of the info is broken
![Screen Shot 2020-06-08 at 3 55 39 PM](https://user-images.githubusercontent.com/20182572/84038742-99e4ed80-a9a0-11ea-9e21-1964d7e98542.png)

**Comment by Vilnite** [comment]
Ranking doesn't work.

**Comment by Vilnite** [comment]
@Hamdy can we please fix ranking?

**Comment by Vilnite** [comment]
Fixed on staging. Thank you.
