### ISSUE TITLE
ACI stealth mode

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/projects_website#84]
Max brought up latest update that current ACI website needs to hide pretty much everything for now (no showing of the projects etc).

Here's my proposal then.
Keep working on staging leaving on production only home/landing page (if possible), looking something like this:

![ComingSoon](https://user-images.githubusercontent.com/20182572/84297694-3dbfcc00-ab4e-11ea-97c1-81b32612689c.png)

@despiegk and Max see if that works.

**Comment by Vilnite** [comment]
Might need to add - Follow ThreeFold News for updates [link to telegram group] or smth like that.

**Comment by maximilianrang** [comment]
That works!

**Comment by Vilnite** [comment]
How about if it's something like this already? ..just a suggestion
(Coming soon.. in Neue Haas Grotesk Display Pro font)

![comingsoon2](https://user-images.githubusercontent.com/20182572/84300698-e7a15780-ab52-11ea-8e14-199507739fdf.png)

**Comment by Hamdy** [comment]
why bother doing so? we have a website already working
doing some upgrades to the UI is not related the functionality of the website! 
whomever the users who saw the website, they saw it already (mostly) so what is the point of disabling functionalities until we have a new design?
also if new design takes like 3, 4 or 5 days , are we  going to loose the users who already knew about the website for the sake of new users who still don't ?
easier choice is to leave the website as is. stop promoting it via our channel, improve then re-promote again

**Comment by Hamdy** [comment]
possible solutions in case we are going to disable website (I don't recommend)
-  temporary disable all links in code and deploy with this intermediate state
- through caddyserver we make it display the coming soon page (static) for that domain [easy]
- other solutions will require adding authentication, and lots of complexities to the website while not needed

**Comment by Vilnite** [comment]
I agree that website without marketing activities and promotion is 'invisible' to the world anyways.

**Comment by Vilnite** [comment]
@despiegk can navigate this best

**Comment by xmonader** [comment]
Only home page shows up in case and when pass code entered you will get access to the full site or a message to reach out to threefold for access.

verified by @despiegk
