### ISSUE TITLE
First result on Google is for staging environment

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/projects_website#85]
<img width="721" alt="Screen Shot 2020-06-12 at 2 46 12 PM" src="https://user-images.githubusercontent.com/50134479/84506176-3ff56800-acbf-11ea-9c2a-4826c44c36cf.png">

Not seeing the normal conscious internet alliance website in the results at all.

**Comment by Vilnite** [comment]
Can someone please check this?
Also - The Alliance for a Conscious Internet , not Conscious Internet Alliance (need to be careful with this)

**Comment by samtaggart** [comment]
@Hamdy Any update here brother?

**Comment by Vilnite** [comment]
No staging on google search. Thank you.
