### ISSUE TITLE
Logo and Name change

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/projects_website#87]
Please replace with the ACI logo on navigation bar:

![ACI_ABR-LOGO](https://user-images.githubusercontent.com/20182572/85125837-9e28ca80-b22c-11ea-99d6-5088e44082c8.png)

Fix the name: The Alliance for a Conscious Internet

And make full logo showing on people/project pages:

![ACI_LOGOTYPE](https://user-images.githubusercontent.com/20182572/85125951-ce706900-b22c-11ea-9e95-619d7577e4fc.png)

![logo_name](https://user-images.githubusercontent.com/20182572/85125979-d7613a80-b22c-11ea-811d-6961ac118234.png)

**Comment by ehab-hassan** [comment]
done at staging but i ll be nice if I have logos in SVG to avoid pixelation

**Comment by Vilnite** [comment]
Here you go @ehab-hassan : https://drive.google.com/drive/folders/1YpI50TErbV02BeYK8px6icdZOox85Xip

**Comment by ehab-hassan** [comment]
@Vilnite thanks SVG updated
