### ISSUE TITLE
Remove password landing from ACI

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/projects_website#89]
Do to some recent events we won't go with hidden approach no more.
**Please remove landing page that requires password.**
Update staging to production and make sure changes we make on GitHub content shows on production.
Thank you.

**Comment by ehab-hassan** [comment]
done at staging
https://staging.consciousinternet.org/#/
@Vilnite please verify
@Hamdy please update production after verification

**Comment by Vilnite** [comment]
Approved. @Hamdy please push to production
