### ISSUE TITLE
vimeo and kristof's channel showing up by default on each video

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/projects_website#9]
![image](https://user-images.githubusercontent.com/64129/80702469-68dfe600-8ae1-11ea-9ada-d57ddcd3bfc0.png)

Let's find a solution if possible otherwise we would have to host these ourselves

![image](https://user-images.githubusercontent.com/64129/80702784-e572c480-8ae1-11ea-832b-dd052d18faed.png)

**Comment by Hamdy** [comment]
done
