### ISSUE TITLE
Logo change in metadata

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/projects_website#93]
Change from ThreeFold icon to ACI

![ACI_ICON](https://user-images.githubusercontent.com/20182572/86244855-3f127080-bbb1-11ea-8a43-b5c09d949e63.png)

![Screen Shot 2020-06-30 at 6 59 13 PM](https://user-images.githubusercontent.com/20182572/86244796-2b670a00-bbb1-11ea-8c3f-ac97e1d9544f.png)

**Comment by ehab-hassan** [comment]
updated at staging

**Comment by Vilnite** [comment]
Perfect. Thanks.
