### ISSUE TITLE
People view fixed

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/projects_website#96]
It looks like sentences are cut super short now, let's give out more of people's bio's, there's room for that.
I'd say 4 lines ending with 2 dots:

"Marcelo Bohrer is a creative thinker, focused on design and innovation, passionate about bringing transformative ideas to life, and use them to make the world a better place. With extensive experience in using design thinking to develop solutions to complex scenarios, he created several .. "  << like this

Plus set alignment for tags, they are way off now.

![Screen Shot 2020-07-16 at 2 31 39 PM](https://user-images.githubusercontent.com/20182572/87671364-897b1c00-c771-11ea-9acd-6a61bbcdca5a.png)

**Comment by samaradel** [comment]
it conflicts with https://github.com/threefoldfoundation/www_conscious_internet/issues/91 .. are you sure?

**Comment by Vilnite** [comment]
Mission statement for projects is short - 1 sentence, so there we don't need dots that indicates that sentence is unfinished, cause it is finished.
P.s. I'll make sure there's a dot at the end of each sentence.

Bio's on the other hand are much longer and we cut them short so we need dots to show that sentence continues.

Yes, please, execute. :)

**Comment by Vilnite** [comment]
works 👍
