### ISSUE TITLE
Image stretch

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/projects_website#97]
I've received feedback on images being stretched when changing screen size:

full size:
![Screen Shot 2020-07-16 at 2 38 57 PM](https://user-images.githubusercontent.com/20182572/87671868-5b4a0c00-c772-11ea-9a33-ba7f155c5f76.png)

smaller screen:
![Screen Shot 2020-07-16 at 2 38 45 PM](https://user-images.githubusercontent.com/20182572/87671925-6b61eb80-c772-11ea-8819-c4234cf6eb11.png)

People page is working well, can you fix this @ehab-hassan ?

**Comment by ehab-hassan** [comment]
fixed at staging

**Comment by Vilnite** [comment]
thank you
